import type { inventoryMachineDTO, ProductionMachineDTO, SghMachineDTO } from '../dto/machineDTO';

interface inventory {
    production: ProductionMachineDTO[],
    storage: inventoryMachineDTO[],
    maintenance: inventoryMachineDTO[],
    bench?: inventoryMachineDTO[],
    discard?: inventoryMachineDTO[]
}

export const machinesDB: inventory = {
    production: [
        {
            id: 1,
            local: 'CLIENTES AMIL',
            workingStation: 'SALA CLIENTE',
            cell: 'CLIENTES AMIL',
            category: 'STAFF',
            asset: 'SEM_ATIVO_MGC_97',
            serial: '9C7H0D3',
            hostname: 'DT9C7H0D3',
            sgh_status: 'Produção'
        },
        {
            id: 2,
            local: 'HOME',
            workingStation: 'BRUNA ARAUJO DIAS',
            cell: 'HOME OFFICE',
            category: 'OPERACIONAL',
            asset: 'SEM_ATIVO_BRF_457',
            serial: '7QWM0D3',
            hostname: 'Não encontrada',
            sgh_status: 'Afastado'
        },
        {
            id: 3,
            local: 'HOME',
            workingStation: 'CAROLINE RODRIGUES PERREIRA',
            cell: 'HOME OFFICE',
            category: 'OPERACIONAL',
            asset: 'N010610',
            serial: '1110L93',
            hostname: '-',
            sgh_status: 'Afastado'
        },
        {
            id: 4,
            local: 'HOME',
            workingStation: 'LARISSA DO NASCIMENTO PEDRO',
            cell: 'HOME OFFICE',
            category: 'OPERACIONAL',
            asset: 'N012175',
            serial: '4LWM0D3',
            hostname: '-',
            sgh_status: 'Afastado'
        },
        {
            id: 5,
            local: 'HOME',
            workingStation: 'Nathalia Ingrid Pantano Ferreira',
            cell: 'HOME OFFICE',
            category: 'OPERACIONAL',
            asset: 'N010336',
            serial: 'FX00L93',
            hostname: 'DTFX00L93',
            sgh_status: 'Afastado'
        },
        {
            id: 6,
            local: 'HOME',
            workingStation: 'SAMANTHA RODRIGUES ROCHA DOS SANTOS',
            cell: 'HOME OFFICE',
            category: 'OPERACIONAL',
            asset: 'N010302',
            serial: 'FS00L93',
            hostname: 'Não encontrada',
            sgh_status: 'Afastado'
        },
        {
            id: 7,
            local: 'HOME',
            workingStation: 'TAYNARA DE SANTANA PULS',
            cell: 'Planejamento',
            category: 'CORPORATIVO',
            asset: 'N011666',
            serial: 'BD7H0D3',
            hostname: 'DTBD7H0D3',
            sgh_status: 'Produção'
        },
        {
            id: 8,
            local: 'HOME',
            workingStation: 'THAYNA OLIVEIRA LOPES',
            cell: 'HOME OFFICE',
            category: 'OPERACIONAL',
            asset: 'N014766',
            serial: '69HVHF3',
            hostname: 'Não encontrada',
            sgh_status: 'Não devolvido'
        },
        {
            id: 9,
            local: 'SALAO PRINCIPAL AMIL',
            workingStation: '1',
            cell: 'OPERACIONAL',
            category: 'OPERACIONAL',
            asset: 'N006076',
            serial: 'BQ28VW2',
            hostname: 'DTBQ28VW2',
            sgh_status: 'Produção'
        },
        {
            id: 10,
            local: 'SALAO PRINCIPAL AMIL',
            workingStation: '2',
            cell: 'OPERACIONAL',
            category: 'OPERACIONAL',
            asset: 'N006006',
            serial: 'BRV7VW2',
            hostname: 'DTBRV7VW2',
            sgh_status: 'Produção'
        },
        {
            id: 11,
            local: 'SALAO PRINCIPAL AMIL',
            workingStation: '3',
            cell: 'OPERACIONAL',
            category: 'OPERACIONAL',
            asset: 'N006842',
            serial: 'BTT4VW2',
            hostname: 'DTBTT4VW2',
            sgh_status: 'Produção'
        },
        {
            id: 12,
            local: 'SALAO PRINCIPAL AMIL',
            workingStation: '4',
            cell: 'OPERACIONAL',
            category: 'OPERACIONAL',
            asset: 'N006022',
            serial: 'BV23VW2',
            hostname: '',
            sgh_status: 'Produção'
        },
        {
            id: 13,
            local: 'SALAO PRINCIPAL AMIL',
            workingStation: '5',
            cell: 'OPERACIONAL',
            category: 'OPERACIONAL',
            asset: 'N006704',
            serial: 'BNZ2VW2',
            hostname: 'DTBNZ2VW2',
            sgh_status: 'Produção'
        },
        {
            id: 14,
            local: 'SALAO PRINCIPAL AMIL',
            workingStation: '6',
            cell: 'OPERACIONAL',
            category: 'OPERACIONAL',
            asset: 'N006192',
            serial: 'BTX6VW2',
            hostname: 'DTBTX6VW2',
            sgh_status: 'Produção'
        },
        {
            id: 15,
            local: 'SALAO PRINCIPAL AMIL',
            workingStation: '7',
            cell: 'OPERACIONAL',
            category: 'OPERACIONAL',
            asset: 'N005795',
            serial: 'BQY8VW2',
            hostname: 'DTBQY8VW2',
            sgh_status: 'Produção'
        },
        {
            id: 16,
            local: 'SALAO PRINCIPAL AMIL',
            workingStation: '8',
            cell: 'OPERACIONAL',
            category: 'OPERACIONAL',
            asset: 'N006709',
            serial: 'BQB1VW2',
            hostname: 'DTBQB1VW2',
            sgh_status: 'Produção'
        },
        {
            id: 17,
            local: 'SALAO PRINCIPAL AMIL',
            workingStation: '9',
            cell: 'OPERACIONAL',
            category: 'OPERACIONAL',
            asset: 'N006005',
            serial: 'BTM6VW2',
            hostname: 'DTBTM6VW2',
            sgh_status: 'Produção'
        },
        {
            id: 18,
            local: 'SALAO PRINCIPAL AMIL',
            workingStation: '10',
            cell: 'OPERACIONAL',
            category: 'OPERACIONAL',
            asset: 'N006053',
            serial: 'BTV1VW2',
            hostname: 'DTBTV1VW2',
            sgh_status: 'Produção'
        },
        {
            id: 19,
            local: 'SALAO PRINCIPAL AMIL',
            workingStation: '11',
            cell: 'OPERACIONAL',
            category: 'OPERACIONAL',
            asset: 'N005760',
            serial: 'BPF1VW2',
            hostname: 'DTBPF1VW2',
            sgh_status: 'Produção'
        },
        {
            id: 20,
            local: 'SALAO PRINCIPAL AMIL',
            workingStation: '12',
            cell: 'OPERACIONAL',
            category: 'OPERACIONAL',
            asset: 'N006670',
            serial: 'BTR1VW2',
            hostname: 'DTBTR1VW2',
            sgh_status: 'Produção'
        },
        {
            id: 21,
            local: 'SALAO PRINCIPAL AMIL',
            workingStation: '13',
            cell: 'OPERACIONAL',
            category: 'OPERACIONAL',
            asset: 'N006803',
            serial: 'BRH9VW2',
            hostname: 'DTBRH9VW2',
            sgh_status: 'Produção'
        },
        {
            id: 22,
            local: 'SALAO PRINCIPAL AMIL',
            workingStation: '14',
            cell: 'OPERACIONAL',
            category: 'OPERACIONAL',
            asset: 'N005821',
            serial: 'BST1VW2',
            hostname: 'DTBST1VW2',
            sgh_status: 'Produção'
        },
        {
            id: 23,
            local: 'SALAO PRINCIPAL AMIL',
            workingStation: '15',
            cell: 'OPERACIONAL',
            category: 'OPERACIONAL',
            asset: 'N005736',
            serial: 'BPJ3VW2',
            hostname: 'DTBPJ3VW2',
            sgh_status: 'Produção'
        },
        {
            id: 24,
            local: 'SALAO PRINCIPAL AMIL',
            workingStation: '16',
            cell: 'OPERACIONAL',
            category: 'OPERACIONAL',
            asset: 'N005733',
            serial: 'BNZ0VW2',
            hostname: 'DTBNZ0VW2',
            sgh_status: 'Produção'
        },
        {
            id: 25,
            local: 'SALAO PRINCIPAL AMIL',
            workingStation: '17',
            cell: 'OPERACIONAL',
            category: 'OPERACIONAL',
            asset: 'N006070',
            serial: 'BSW4VW2',
            hostname: 'DTBSW4VW2',
            sgh_status: 'Produção'
        },
        {
            id: 26,
            local: 'SALAO PRINCIPAL AMIL',
            workingStation: '18',
            cell: 'OPERACIONAL',
            category: 'OPERACIONAL',
            asset: 'N005814',
            serial: 'BQ14VW2',
            hostname: 'DTBQ14VW2',
            sgh_status: 'Produção'
        },
        {
            id: 27,
            local: 'SALAO PRINCIPAL AMIL',
            workingStation: '19',
            cell: 'OPERACIONAL',
            category: 'OPERACIONAL',
            asset: 'N005820',
            serial: 'BSX6VW2',
            hostname: 'DTBSX6VW2A',
            sgh_status: 'Produção'
        },
        {
            id: 28,
            local: 'SALAO PRINCIPAL AMIL',
            workingStation: '20',
            cell: 'OPERACIONAL',
            category: 'OPERACIONAL',
            asset: 'N006800',
            serial: 'BPX7VW2',
            hostname: 'DTBPX7VW2',
            sgh_status: 'Produção'
        },
        {
            id: 29,
            local: 'SALAO PRINCIPAL AMIL',
            workingStation: '21',
            cell: 'OPERACIONAL',
            category: 'OPERACIONAL',
            asset: 'N005722',
            serial: 'BR36VW2',
            hostname: 'DTBR36VW2',
            sgh_status: 'Produção'
        },
        {
            id: 30,
            local: 'SALAO PRINCIPAL AMIL',
            workingStation: '22',
            cell: 'OPERACIONAL',
            category: 'OPERACIONAL',
            asset: 'N005811',
            serial: 'BR96VW2',
            hostname: 'DTBR96VW2',
            sgh_status: 'Produção'
        },
    ],
    storage: [
        {
            id: 1,
            asset: 'N005819',
            serial: 'BRY0VW2',
            model: 'OptiPlex 3060',
            manufacturer: 'Dell Inc.',
            type: 'Desktop',
            sgh_status: 'Estoque',
            hostname: 'DTBRY0VW2',
            observation: ''
        },
        {
            id: 2,
            asset: 'N006891',
            serial: 'BRH3VW2',
            model: 'OptiPlex 3060',
            manufacturer: 'Dell Inc.',
            type: 'Desktop',
            sgh_status: 'Estoque',
            hostname: 'DTBRH3VW2',
            observation: ''
        },
        {
            id: 3,
            asset: 'SEM_ATIVO_J23_223',
            serial: '6VYJ2M2',
            model: 'OptiPlex 3050',
            manufacturer: 'Dell Inc.',
            type: 'Desktop',
            sgh_status: 'Estoque',
            hostname: 'OK',
            observation: ''
        },
        {
            id: 4,
            asset: 'N006036',
            serial: 'BVD8VW2',
            model: 'OptiPlex 3060',
            manufacturer: 'Dell Inc.',
            type: 'Desktop',
            sgh_status: 'Estoque',
            hostname: 'OK',
            observation: ''
        },
        {
            id: 5,
            asset: 'N007344',
            serial: 'BRK8VW2',
            model: 'OptiPlex 3060',
            manufacturer: 'Dell Inc.',
            type: 'Desktop',
            sgh_status: 'Estoque',
            hostname: 'OK',
            observation: ''
        },
        {
            id: 6,
            asset: 'SEM_ATIVO_BRF_876',
            serial: '95QH2M2',
            model: 'OptiPlex 3050',
            manufacturer: 'Dell Inc.',
            type: 'Desktop',
            sgh_status: 'Estoque',
            hostname: 'OK',
            observation: ''
        },
        {
            id: 7,
            asset: 'SEM_ATIVO_9536',
            serial: '29RMSL2',
            model: 'OptiPlex 3050',
            manufacturer: 'Dell Inc.',
            type: 'Desktop',
            sgh_status: 'Estoque',
            hostname: 'OK',
            observation: ''
        },
        {
            id: 8,
            asset: 'SEM_ATIVO_BRF_969',
            serial: '93VJ2M2',
            model: 'OptiPlex 3050',
            manufacturer: 'Dell Inc.',
            type: 'Desktop',
            sgh_status: 'Estoque',
            hostname: 'OK',
            observation: ''
        },
        {
            id: 9,
            asset: 'SEM_ATIVO_BRF_812',
            serial: 'DJ6DSL2',
            model: 'OptiPlex 3050',
            manufacturer: 'Dell Inc.',
            type: 'Desktop',
            sgh_status: 'Estoque',
            hostname: 'OK',
            observation: 'ultima mini'
        },
        {
            id: 10,
            asset: 'SEM_ATIVO_J23_6097',
            serial: '1TXBY02',
            model: 'Optiplex 3020',
            manufacturer: 'Dell Inc.',
            type: 'Desktop',
            sgh_status: 'Estoque',
            hostname: 'OK',
            observation: ''
        },
        {
            id: 11,
            asset: 'SEM_ATIVO_J23_6101',
            serial: '18RCY02',
            model: 'Optiplex 3020',
            manufacturer: 'Dell Inc.',
            type: 'Desktop',
            sgh_status: 'Estoque',
            hostname: 'OK',
            observation: ''
        },
        {
            id: 12,
            asset: 'SEM_ATIVO_J23_6073',
            serial: '51JCY02',
            model: 'Optiplex 3020',
            manufacturer: 'Dell Inc.',
            type: 'Desktop',
            sgh_status: 'Estoque',
            hostname: 'OK',
            observation: ''
        },
        {
            id: 13,
            asset: 'SEM_ATIVO_MGC_6005',
            serial: 'GZ2CY02',
            model: 'Optiplex 3020',
            manufacturer: 'Dell Inc.',
            type: 'Desktop',
            sgh_status: 'Estoque',
            hostname: 'OK',
            observation: ''
        },
        {
            id: 14,
            asset: 'SEM_ATIVO_JBT_6200',
            serial: 'GWXN172',
            model: 'Optiplex 3020',
            manufacturer: 'Dell Inc.',
            type: 'Desktop',
            sgh_status: 'Estoque',
            hostname: 'OK',
            observation: ''
        },
        {
            id: 15,
            asset: 'A093194',
            serial: '2JBDLZ1',
            model: 'Optiplex 3020',
            manufacturer: 'Dell Inc.',
            type: 'Desktop',
            sgh_status: 'Estoque',
            hostname: 'OK',
            observation: ''
        },
        {
            id: 16,
            asset: 'SEM_ATIVO_J23_6099',
            serial: '9F04Y02',
            model: 'Optiplex 3020',
            manufacturer: 'Dell Inc.',
            type: 'Desktop',
            sgh_status: 'Estoque',
            hostname: 'OK',
            observation: ''
        },
        {
            id: 17,
            asset: 'SEM_ATIVO_J23_6100',
            serial: '7H04Y02',
            model: 'Optiplex 3020',
            manufacturer: 'Dell Inc.',
            type: 'Desktop',
            sgh_status: 'Estoque',
            hostname: 'OK',
            observation: ''
        },
        {
            id: 18,
            asset: 'SEM_ATIVO_J23_6096',
            serial: '35YBY02',
            model: 'Optiplex 3020',
            manufacturer: 'Dell Inc.',
            type: 'Desktop',
            sgh_status: 'Estoque',
            hostname: 'OK',
            observation: 'ultima under table'
        },
        {
            id: 19,
            asset: 'N012163',
            serial: 'DNWM0D3',
            model: 'OptiPlex 3080',
            manufacturer: 'Dell Inc.',
            type: 'Desktop',
            sgh_status: 'Estoque',
            hostname: 'DTGNWM0D3',
            observation: ''
        },
        {
            id: 20,
            asset: 'A107017',
            serial: 'CSH1SP2',
            model: 'OptiPlex 3050',
            manufacturer: 'Dell Inc.',
            type: 'Desktop',
            sgh_status: 'Estoque',
            hostname: 'OK',
            observation: ''
        },
        {
            id: 21,
            asset: 'SEM_ATIVO_STS_715',
            serial: 'CTM1SP2',
            model: 'OptiPlex 3050',
            manufacturer: 'Dell Inc.',
            type: 'Desktop',
            sgh_status: 'Estoque',
            hostname: 'OK',
            observation: ''
        },
        {
            id: 22,
            asset: 'SEM_ATIVO_STS_52',
            serial: 'GS3H0D3',
            model: 'OptiPlex 3080',
            manufacturer: 'Dell Inc.',
            type: 'Desktop',
            sgh_status: 'Estoque',
            hostname: 'DTGS3H0D3',
            observation: 'ultima 3080'
        },
        {
            id: 23,
            asset: 'SEM_ATIVO_SJO_193',
            serial: '4A617C670',
            model: 'Positivo Master D3100',
            manufacturer: 'Positivo SA',
            type: 'Desktop',
            sgh_status: 'Estoque',
            hostname: 'OK',
            observation: ''
        },
        {
            id: 24,
            asset: 'N004303',
            serial: '4A607LQ1H',
            model: 'Positivo Master D3100',
            manufacturer: 'Positivo SA',
            type: 'Desktop',
            sgh_status: 'Estoque',
            hostname: 'OK',
            observation: ''
        },
        {
            id: 25,
            asset: 'N004943',
            serial: '4A609H617',
            model: 'Positivo Master D3100',
            manufacturer: 'Positivo SA',
            type: 'Desktop',
            sgh_status: 'Estoque',
            hostname: 'OK',
            observation: ''
        },
        {
            id: 26,
            asset: 'N004976',
            serial: '4A617CL2K',
            model: 'Positivo Master D3100',
            manufacturer: 'Positivo SA',
            type: 'Desktop',
            sgh_status: 'Estoque',
            hostname: 'OK',
            observation: ''
        },
        {
            id: 27,
            asset: 'a095031',
            serial: 'JCV23V1',
            model: 'OptiPlex 3010',
            manufacturer: 'Dell Inc.',
            type: 'Desktop',
            sgh_status: 'Estoque',
            hostname: 'OK',
            observation: ''
        },
        {
            id: 28,
            asset: 'A108548',
            serial: '11W8LZ1',
            model: 'OptiPlex 3010',
            manufacturer: 'Dell Inc.',
            type: 'Desktop',
            sgh_status: 'Estoque',
            hostname: 'OK',
            observation: ''
        },
        {
            id: 29,
            asset: 'SEM_ATIVO_JBT_6234',
            serial: 'D0PTZX1',
            model: 'OptiPlex 3010',
            manufacturer: 'Dell Inc.',
            type: 'Desktop',
            sgh_status: 'Estoque',
            hostname: 'OK',
            observation: ''
        },
        {
            id: 30,
            asset: 'A106365',
            serial: '34SZZX1',
            model: 'OptiPlex 3010',
            manufacturer: 'Dell Inc.',
            type: 'Desktop',
            sgh_status: 'Estoque',
            hostname: 'OK',
            observation: ''
        },
        {
            id: 31,
            asset: 'SEM_ATIVO_J23_6016',
            serial: '61R10Y1',
            model: 'OptiPlex 3010',
            manufacturer: 'Dell Inc.',
            type: 'Desktop',
            sgh_status: 'Estoque',
            hostname: 'OK',
            observation: ''
        },
        {
            id: 32,
            asset: 'SEM_ATIVO_MGC_111',
            serial: 'HKJG6W1',
            model: 'OptiPlex 3010',
            manufacturer: 'Dell Inc.',
            type: 'Desktop',
            sgh_status: 'Estoque',
            hostname: 'OK',
            observation: ''
        },
        {
            id: 33,
            asset: 'SEM_ATIVO_J23_444',
            serial: '71L40Y1',
            model: 'OptiPlex 3010',
            manufacturer: 'Dell Inc.',
            type: 'Desktop',
            sgh_status: 'Estoque',
            hostname: 'OK',
            observation: ''
        },
        {
            id: 34,
            asset: 'A114602',
            serial: 'GV79LZ1',
            model: 'OptiPlex 3010',
            manufacturer: 'Dell Inc.',
            type: 'Desktop',
            sgh_status: 'Estoque',
            hostname: 'OK',
            observation: ''
        },
        {
            id: 35,
            asset: 'SEM_ATIVO_MGC_142',
            serial: '5CV23V1',
            model: 'OptiPlex 3010',
            manufacturer: 'Dell Inc.',
            type: 'Desktop',
            sgh_status: 'Estoque',
            hostname: 'OK',
            observation: ''
        },
        {
            id: 36,
            asset: 'A093571',
            serial: 'HWK40Y1',
            model: 'OptiPlex 3010',
            manufacturer: 'Dell Inc.',
            type: 'Desktop',
            sgh_status: 'Estoque',
            hostname: 'OK',
            observation: ''
        },
        {
            id: 37,
            asset: 'SEM_ATIVO_MGC_7001',
            serial: 'DYKD6W1',
            model: 'OptiPlex 3010',
            manufacturer: 'Dell Inc.',
            type: 'Desktop',
            sgh_status: 'Estoque',
            hostname: 'OK',
            observation: ''
        },
        {
            id: 38,
            asset: 'SEM_ATIVO_299',
            serial: 'HGFL6W1',
            model: 'OptiPlex 3010',
            manufacturer: 'Dell Inc.',
            type: 'Desktop',
            sgh_status: 'Estoque',
            hostname: 'OK',
            observation: ''
        },
        {
            id: 39,
            asset: 'A106632',
            serial: '1JL40Y1',
            model: 'OptiPlex 3010',
            manufacturer: 'Dell Inc.',
            type: 'Desktop',
            sgh_status: 'Estoque',
            hostname: 'OK',
            observation: ''
        },
        {
            id: 40,
            asset: 'SEM_ATIVO_SJO_4001',
            serial: 'HV1F0Y1',
            model: 'OptiPlex 3010',
            manufacturer: 'Dell Inc.',
            type: 'Desktop',
            sgh_status: 'Estoque',
            hostname: 'OK',
            observation: ''
        },
        {
            id: 41,
            asset: 'A093789',
            serial: '9TK40Y1',
            model: 'OptiPlex 3010',
            manufacturer: 'Dell Inc.',
            type: 'Desktop',
            sgh_status: 'Estoque',
            hostname: 'OK',
            observation: 'primera coluna'
        },
        {
            id: 42,
            asset: 'SEM_ATIVO_STS_312',
            serial: '4A609GZ1F',
            model: 'Positivo Master D3100',
            manufacturer: 'Positivo SA',
            type: 'Desktop',
            sgh_status: 'Estoque',
            hostname: 'OK',
            observation: ''
        },
        {
            id: 43,
            asset: 'N005453',
            serial: '4A6069L3X',
            model: 'Positivo Master D3100',
            manufacturer: 'Positivo SA',
            type: 'Desktop',
            sgh_status: 'Estoque',
            hostname: 'OK',
            observation: ''
        },
        {
            id: 44,
            asset: 'SEM_ATIVO_SJO_168',
            serial: '4A6069N7N',
            model: 'Positivo Master D3100',
            manufacturer: 'Positivo SA',
            type: 'Desktop',
            sgh_status: 'Estoque',
            hostname: 'OK',
            observation: ''
        },
        {
            id: 45,
            asset: 'A114730',
            serial: '4A617C73J',
            model: 'Positivo Master D3100',
            manufacturer: 'Positivo SA',
            type: 'Desktop',
            sgh_status: 'Estoque',
            hostname: 'OK',
            observation: ''
        },
        {
            id: 46,
            asset: 'SEM_ATIVO_MGC_5506',
            serial: '8KJG6W1',
            model: 'OptiPlex 3010',
            manufacturer: 'Dell Inc.',
            type: 'Desktop',
            sgh_status: 'Estoque',
            hostname: 'OK',
            observation: ''
        },
        {
            id: 47,
            asset: 'SEM_ATIVO_MGC_6002',
            serial: '50QWZX1',
            model: 'OptiPlex 3010',
            manufacturer: 'Dell Inc.',
            type: 'Desktop',
            sgh_status: 'Estoque',
            hostname: 'OK',
            observation: ''
        },
        {
            id: 48,
            asset: 'SEM_ATIVO_9529',
            serial: 'JK4GLZ1',
            model: 'OptiPlex 3010',
            manufacturer: 'Dell Inc.',
            type: 'Desktop',
            sgh_status: 'Estoque',
            hostname: 'OK',
            observation: ''
        },
        {
            id: 49,
            asset: 'SEM_ATIVO_295',
            serial: '6VLD6W1',
            model: 'OptiPlex 3010',
            manufacturer: 'Dell Inc.',
            type: 'Desktop',
            sgh_status: 'Estoque',
            hostname: 'OK',
            observation: ''
        },
        {
            id: 50,
            asset: 'SEM_ATIVO_MGC_188',
            serial: 'HBKD6W1',
            model: 'OptiPlex 3010',
            manufacturer: 'Dell Inc.',
            type: 'Desktop',
            sgh_status: 'Estoque',
            hostname: 'OK',
            observation: ''
        },
        {
            id: 51,
            asset: 'A095033',
            serial: 'G45LSV1',
            model: 'OptiPlex 3010',
            manufacturer: 'Dell Inc.',
            type: 'Desktop',
            sgh_status: 'Estoque',
            hostname: 'OK',
            observation: ''
        },
        {
            id: 52,
            asset: 'N110373',
            serial: '14L40Y1',
            model: 'OptiPlex 3010',
            manufacturer: 'Dell Inc.',
            type: 'Desktop',
            sgh_status: 'Estoque',
            hostname: 'OK',
            observation: ''
        },
        {
            id: 53,
            asset: 'A114113',
            serial: '3V7FLZ1',
            model: 'OptiPlex 3010',
            manufacturer: 'Dell Inc.',
            type: 'Desktop',
            sgh_status: 'Estoque',
            hostname: 'OK',
            observation: ''
        },
        {
            id: 54,
            asset: 'A106007',
            serial: 'H4L20Y1',
            model: 'OptiPlex 3010',
            manufacturer: 'Dell Inc.',
            type: 'Desktop',
            sgh_status: 'Estoque',
            hostname: 'OK',
            observation: ''
        },
        {
            id: 55,
            asset: 'SEM_ATIVO_J23_323',
            serial: '342G0Y1',
            model: 'OptiPlex 3010',
            manufacturer: 'Dell Inc.',
            type: 'Desktop',
            sgh_status: 'Estoque',
            hostname: 'OK',
            observation: ''
        },
        {
            id: 56,
            asset: 'A100314',
            serial: 'GBK20Y1',
            model: 'OptiPlex 3010',
            manufacturer: 'Dell Inc.',
            type: 'Desktop',
            sgh_status: 'Estoque',
            hostname: 'OK',
            observation: ''
        },
        {
            id: 57,
            asset: 'SEM_ATIVO_J23_236',
            serial: 'D1PTZX1',
            model: 'OptiPlex 3010',
            manufacturer: 'Dell Inc.',
            type: 'Desktop',
            sgh_status: 'Estoque',
            hostname: 'OK',
            observation: ''
        },
        {
            id: 58,
            asset: 'A104794',
            serial: '7GFL6W1',
            model: 'OptiPlex 3010',
            manufacturer: 'Dell Inc.',
            type: 'Desktop',
            sgh_status: 'Estoque',
            hostname: 'OK',
            observation: ''
        },
        {
            id: 59,
            asset: 'SEM_ATIVO_280',
            serial: '6BK20Y1',
            model: 'OptiPlex 3010',
            manufacturer: 'Dell Inc.',
            type: 'Desktop',
            sgh_status: 'Estoque',
            hostname: 'OK',
            observation: ''
        },
        {
            id: 60,
            asset: 'N003273',
            serial: 'CFKG6W1',
            model: 'OptiPlex 3010',
            manufacturer: 'Dell Inc.',
            type: 'Desktop',
            sgh_status: 'Estoque',
            hostname: 'OK',
            observation: 'segunda coluna'
        },
        {
            id: 61,
            asset: 'SEM_ATIVO_MGC_151',
            serial: '57R00Y1',
            model: 'OptiPlex 3010',
            manufacturer: 'Dell Inc.',
            type: 'Desktop',
            sgh_status: 'Estoque',
            hostname: 'OK',
            observation: ''
        },
        {
            id: 62,
            asset: 'A099162',
            serial: '15TBLZ1',
            model: 'OptiPlex 3010',
            manufacturer: 'Dell Inc.',
            type: 'Desktop',
            sgh_status: 'Estoque',
            hostname: 'OK',
            observation: ''
        },
        {
            id: 63,
            asset: 'SEM_ATIVO_308',
            serial: 'GC3MZX1',
            model: 'OptiPlex 3010',
            manufacturer: 'Dell Inc.',
            type: 'Desktop',
            sgh_status: 'Estoque',
            hostname: 'OK',
            observation: ''
        },
        {
            id: 64,
            asset: 'A108468',
            serial: '71PQZX1',
            model: 'OptiPlex 3010',
            manufacturer: 'Dell Inc.',
            type: 'Desktop',
            sgh_status: 'Estoque',
            hostname: 'OK',
            observation: ''
        },
        {
            id: 65,
            asset: 'SEM_ATIVO_276',
            serial: '94VBLZ1',
            model: 'OptiPlex 3010',
            manufacturer: 'Dell Inc.',
            type: 'Desktop',
            sgh_status: 'Estoque',
            hostname: 'OK',
            observation: ''
        },
        {
            id: 66,
            asset: 'SEM_ATIVO_9527',
            serial: '4NSF6W1',
            model: 'OptiPlex 3010',
            manufacturer: 'Dell Inc.',
            type: 'Desktop',
            sgh_status: 'Estoque',
            hostname: 'OK',
            observation: ''
        },
        {
            id: 67,
            asset: 'A114097',
            serial: '7T7BLZ1',
            model: 'OptiPlex 3010',
            manufacturer: 'Dell Inc.',
            type: 'Desktop',
            sgh_status: 'Estoque',
            hostname: 'OK',
            observation: ''
        },
        {
            id: 68,
            asset: 'A114561',
            serial: '4RCM6W1',
            model: 'OptiPlex 3010',
            manufacturer: 'Dell Inc.',
            type: 'Desktop',
            sgh_status: 'Estoque',
            hostname: 'OK',
            observation: ''
        },
        {
            id: 69,
            asset: 'N001015',
            serial: '80PRZX1',
            model: 'OptiPlex 3010',
            manufacturer: 'Dell Inc.',
            type: 'Desktop',
            sgh_status: 'Estoque',
            hostname: 'OK',
            observation: ''
        },
        {
            id: 70,
            asset: 'SEM_ATIVO_306',
            serial: '2DJ30Y1',
            model: 'OptiPlex 3010',
            manufacturer: 'Dell Inc.',
            type: 'Desktop',
            sgh_status: 'Estoque',
            hostname: 'OK',
            observation: ''
        },
        {
            id: 71,
            asset: 'SEM_ATIVO_MGC_220',
            serial: 'BPLD6W1',
            model: 'OptiPlex 3010',
            manufacturer: 'Dell Inc.',
            type: 'Desktop',
            sgh_status: 'Estoque',
            hostname: 'OK',
            observation: ''
        },
        {
            id: 72,
            asset: 'A106531',
            serial: 'D2QYZX1',
            model: 'OptiPlex 3010',
            manufacturer: 'Dell Inc.',
            type: 'Desktop',
            sgh_status: 'Estoque',
            hostname: 'OK',
            observation: ''
        },
        {
            id: 73,
            asset: 'a120890',
            serial: 'DZHG6W1',
            model: 'OptiPlex 3010',
            manufacturer: 'Dell Inc.',
            type: 'Desktop',
            sgh_status: 'Estoque',
            hostname: 'OK',
            observation: ''
        },
        {
            id: 74,
            asset: 'A100745',
            serial: '6VK10Y1',
            model: 'OptiPlex 3010',
            manufacturer: 'Dell Inc.',
            type: 'Desktop',
            sgh_status: 'Estoque',
            hostname: 'OK',
            observation: ''
        },
        {
            id: 75,
            asset: 'A105230',
            serial: '4YV8LZ1',
            model: 'OptiPlex 3010',
            manufacturer: 'Dell Inc.',
            type: 'Desktop',
            sgh_status: 'Estoque',
            hostname: 'OK',
            observation: ''
        },
        {
            id: 76,
            asset: 'SEM_ATIVO_MGC_206',
            serial: '5FJ30Y1',
            model: 'OptiPlex 3010',
            manufacturer: 'Dell Inc.',
            type: 'Desktop',
            sgh_status: 'Estoque',
            hostname: 'OK',
            observation: ''
        },
        {
            id: 77,
            asset: 'SEM_ATIVO_9100',
            serial: 'DFKG6W1',
            model: 'OptiPlex 3010',
            manufacturer: 'Dell Inc.',
            type: 'Desktop',
            sgh_status: 'Estoque',
            hostname: 'OK',
            observation: 'terceira coluna'
        },
        {
            id: 78,
            asset: 'N013623',
            serial: 'PE094TV6',
            model: 'Lenovo E14',
            manufacturer: 'Lenovo',
            type: 'Notebook',
            sgh_status: 'Estoque',
            hostname: 'OK',
            observation: 'NOTEBOOK'
        },
        {
            id: 79,
            asset: 'N000015',
            serial: 'PE02PDHK',
            model: 'ThinkPad T460 Laptop',
            manufacturer: 'Lenovo',
            type: 'Notebook',
            sgh_status: 'Estoque',
            hostname: 'OK',
            observation: 'NOTEBOOK'
        },
        {
            id: 80,
            asset: 'N013469',
            serial: '58PLMJ3',
            model: 'Latitude 3420',
            manufacturer: 'Dell Inc.',
            type: 'Notebook',
            sgh_status: 'Estoque',
            hostname: 'OK',
            observation: 'NOTEBOOK'
        },
        {
            id: 81,
            asset: 'A122917',
            serial: 'PE01G7GM',
            model: 'ThinkPad L440',
            manufacturer: 'Lenovo',
            type: 'Notebook',
            sgh_status: 'Estoque',
            hostname: 'OK',
            observation: 'NOTEBOOK'
        },
        {
            id: 82,
            asset: 'N013465',
            serial: '9NPLMJ3',
            model: 'Latitude 3420',
            manufacturer: 'Dell Inc.',
            type: 'Notebook',
            sgh_status: 'Estoque',
            hostname: 'OK',
            observation: 'NOTEBOOK BRUNA'
        }
    ],
    maintenance: [
        {
            id: 1,
            asset: 'Lenovo',
            serial: 'Mini PC',
            model: 'M720Q',
            manufacturer: 'N009798',
            type: 'PE05MVXJ',
            sgh_status: 'Manutenção',
            hostname: 'DTPE05MVXJ',
            observation: ''
        },
        {
            id: 2,
            asset: 'Dell Inc.',
            serial: 'Desktop',
            model: 'OptiPlex 3060',
            manufacturer: 'N006711',
            type: 'BPV1VW2',
            sgh_status: 'Manutenção',
            hostname: 'OK',
            observation: ''
        },
        {
            id: 3,
            asset: 'Dell Inc.',
            serial: 'Desktop',
            model: 'OptiPlex 3060',
            manufacturer: 'N006067',
            type: 'BQC2VW2',
            sgh_status: 'Manutenção',
            hostname: 'OK',
            observation: ''
        },
        {
            id: 4,
            asset: 'Dell Inc.',
            serial: 'Desktop',
            model: 'OptiPlex 3060',
            manufacturer: 'N005738',
            type: 'BQK9VW2',
            sgh_status: 'Manutenção',
            hostname: 'OK',
            observation: ''
        },
        {
            id: 5,
            asset: 'Dell Inc.',
            serial: 'Desktop',
            model: 'OptiPlex 3060',
            manufacturer: 'N006820',
            type: 'BPH8VW2',
            sgh_status: 'Manutenção',
            hostname: 'OK',
            observation: ''
        },
        {
            id: 6,
            asset: 'Dell Inc.',
            serial: 'Desktop',
            model: 'OptiPlex 3060',
            manufacturer: 'N006233',
            type: '9YQ2VW2',
            sgh_status: 'Manutenção',
            hostname: 'OK',
            observation: ''
        },
        {
            id: 7,
            asset: 'Dell Inc.',
            serial: 'Desktop',
            model: 'OptiPlex 3060',
            manufacturer: 'N005739',
            type: 'BNW0VW2',
            sgh_status: 'Manutenção',
            hostname: 'OK',
            observation: ''
        },
        {
            id: 8,
            asset: 'Dell Inc.',
            serial: 'Desktop',
            model: 'OptiPlex 3060',
            manufacturer: 'N007255',
            type: 'BR62VW2',
            sgh_status: 'Manutenção',
            hostname: 'OK',
            observation: ''
        },
        {
            id: 9,
            asset: 'Dell Inc.',
            serial: 'Desktop',
            model: 'OptiPlex 3060',
            manufacturer: 'N006098',
            type: 'BQV1VW2',
            sgh_status: 'Manutenção',
            hostname: 'OK',
            observation: ''
        },
        {
            id: 10,
            asset: 'Dell Inc.',
            serial: 'Desktop',
            model: 'OptiPlex 3060',
            manufacturer: 'N006049',
            type: 'BT07VW2',
            sgh_status: 'Manutenção',
            hostname: 'OK',
            observation: ''
        },
        {
            id: 11,
            asset: 'Dell Inc.',
            serial: 'Desktop',
            model: 'OptiPlex 3060',
            manufacturer: 'N006030',
            type: 'BT38VW2',
            sgh_status: 'Manutenção',
            hostname: 'OK',
            observation: ''
        },
        {
            id: 12,
            asset: 'Dell Inc.',
            serial: 'Desktop',
            model: 'OptiPlex 3050',
            manufacturer: 'SEM_ATIVO_BRF_818',
            type: 'DJ5FSL2',
            sgh_status: 'Manutenção',
            hostname: 'OK',
            observation: ''
        },
        {
            id: 13,
            asset: 'Dell Inc.',
            serial: 'Desktop',
            model: 'OptiPlex 3050',
            manufacturer: 'SEM_ATIVO_BRF_756',
            type: 'DGJKSL2',
            sgh_status: 'Manutenção',
            hostname: 'OK',
            observation: ''
        },
        {
            id: 14,
            asset: 'Dell Inc.',
            serial: 'Desktop',
            model: 'OptiPlex 3060',
            manufacturer: 'N007170',
            type: 'BPS6VW2',
            sgh_status: 'Manutenção',
            hostname: 'OK',
            observation: ''
        },
        {
            id: 15,
            asset: 'Positivo SA',
            serial: 'Mini PC',
            model: 'Positivo Master C6300',
            manufacturer: 'SEM_ATIVO_SJC_83',
            type: '5A254LS38',
            sgh_status: 'Manutenção',
            hostname: 'OK',
            observation: ''
        },
        {
            id: 16,
            asset: 'Positivo SA',
            serial: 'Mini PC',
            model: 'Positivo Master C6300',
            manufacturer: 'SEM_ATIVO_SJC_87',
            type: '5A253CQ38',
            sgh_status: 'Manutenção',
            hostname: 'OK',
            observation: ''
        },
        {
            id: 17,
            asset: 'Lenovo',
            serial: 'Mini PC',
            model: 'M80q',
            manufacturer: 'N014134',
            type: 'PE098ZE2',
            sgh_status: 'Manutenção',
            hostname: 'OK',
            observation: ''
        },
        {
            id: 18,
            asset: 'Lenovo',
            serial: 'Mini PC',
            model: 'M720Q',
            manufacturer: 'SEM_ATIVO_SJO_585',
            type: 'PE0541ZL',
            sgh_status: 'Manutenção',
            hostname: 'OK',
            observation: ''
        },
        {
            id: 19,
            asset: 'Positivo SA',
            serial: 'Mini PC',
            model: 'Positivo Master C6300',
            manufacturer: 'N014305',
            type: '5A254LV2C',
            sgh_status: 'Manutenção',
            hostname: 'OK',
            observation: ''
        },
        {
            id: 20,
            asset: 'Lenovo',
            serial: 'Mini PC',
            model: 'M720Q',
            manufacturer: 'N009994',
            type: 'PE05MVY7',
            sgh_status: 'Manutenção',
            hostname: 'OK',
            observation: ''
        },
        {
            id: 21,
            asset: 'Lenovo',
            serial: 'Mini PC',
            model: 'M720Q',
            manufacturer: 'SEM_ATIVO_SJO_433',
            type: 'PE05N63T',
            sgh_status: 'Manutenção',
            hostname: 'OK',
            observation: ''
        },
        {
            id: 22,
            asset: 'Positivo SA',
            serial: 'Mini PC',
            model: 'Positivo Master C6300',
            manufacturer: 'SEM_ATIVO_SJC_69',
            type: '5A254LH6Q',
            sgh_status: 'Manutenção',
            hostname: 'OK',
            observation: ''
        },
        {
            id: 23,
            asset: 'Positivo SA',
            serial: 'Mini PC',
            model: 'Positivo Master C6300',
            manufacturer: 'N014347',
            type: '5A254LJ9B',
            sgh_status: 'Manutenção',
            hostname: 'OK',
            observation: ''
        },
        {
            id: 24,
            asset: 'Positivo SA',
            serial: 'Mini PC',
            model: 'Positivo Master C6300',
            manufacturer: 'N014002',
            type: '5A254LL9H',
            sgh_status: 'Manutenção',
            hostname: 'OK',
            observation: ''
        },
        {
            id: 25,
            asset: 'Positivo SA',
            serial: 'Mini PC',
            model: 'Positivo Master C6300',
            manufacturer: 'N015952',
            type: '5A254KW13',
            sgh_status: 'Manutenção',
            hostname: 'OK',
            observation: ''
        },
        {
            id: 26,
            asset: 'Positivo SA',
            serial: 'Mini PC',
            model: 'Positivo Master C6300',
            manufacturer: 'SEM_ATIVO_SJC_103',
            type: '5A2483P64',
            sgh_status: 'Manutenção',
            hostname: 'OK',
            observation: 'ultima mini'
        },
        {
            id: 27,
            asset: 'Dell Inc.',
            serial: 'Desktop',
            model: 'OptiPlex 3010',
            manufacturer: 'SEM_ATIVO_9412',
            type: '3GW7LZ1',
            sgh_status: 'Manutenção',
            hostname: 'OK',
            observation: ''
        },
        {
            id: 28,
            asset: 'Dell Inc.',
            serial: 'Desktop',
            model: 'OptiPlex 3010',
            manufacturer: 'A104321',
            type: 'BNL00Y1',
            sgh_status: 'Manutenção',
            hostname: 'OK',
            observation: ''
        },
        {
            id: 29,
            asset: 'Dell Inc.',
            serial: 'Desktop',
            model: 'OptiPlex 3010',
            manufacturer: 'SEM_ATIVO_J23_260',
            type: 'BT6CLZ1',
            sgh_status: 'Manutenção',
            hostname: 'OK',
            observation: ''
        },
        {
            id: 30,
            asset: 'Dell Inc.',
            serial: 'Desktop',
            model: 'OptiPlex 3010',
            manufacturer: 'A630210',
            type: '5K3HLZ1',
            sgh_status: 'Manutenção',
            hostname: 'OK',
            observation: ''
        },
        {
            id: 31,
            asset: 'Dell Inc.',
            serial: 'Desktop',
            model: 'OptiPlex 3010',
            manufacturer: 'A105665',
            type: 'HT77LZ1',
            sgh_status: 'Manutenção',
            hostname: 'OK',
            observation: 'primeira coluna'
        },
        {
            id: 32,
            asset: 'Dell Inc.',
            serial: 'Desktop',
            model: 'OptiPlex 3050',
            manufacturer: 'SEM_ATIVO_STS_385',
            type: 'CRQVRP2',
            sgh_status: 'Manutenção',
            hostname: 'OK',
            observation: ''
        },
        {
            id: 33,
            asset: 'Dell Inc.',
            serial: 'Desktop',
            model: 'OptiPlex 3080',
            manufacturer: 'SEM_ATIVO_J23_16',
            type: '7LLF0D3',
            sgh_status: 'Manutenção',
            hostname: 'OK',
            observation: ''
        },
        {
            id: 34,
            asset: 'Dell Inc.',
            serial: 'Desktop',
            model: 'OptiPlex 3080',
            manufacturer: 'SEM_ATIVO_STS_953',
            type: 'BLLF0D3',
            sgh_status: 'Manutenção',
            hostname: 'OK',
            observation: ''
        },
        {
            id: 35,
            asset: 'Dell Inc.',
            serial: 'Desktop',
            model: 'OptiPlex 3080',
            manufacturer: 'SEM_ATIVO_MGC_459',
            type: '524H0D3',
            sgh_status: 'Manutenção',
            hostname: 'OK',
            observation: ''
        },
        {
            id: 36,
            asset: 'Dell Inc.',
            serial: 'Desktop',
            model: 'Optiplex 3020',
            manufacturer: 'N012381',
            type: 'FRXBY02',
            sgh_status: 'Manutenção',
            hostname: 'OK',
            observation: ''
        },
        {
            id: 37,
            asset: 'Dell Inc.',
            serial: 'Desktop',
            model: 'OptiPlex 3080',
            manufacturer: 'N011701',
            type: '364H0D3',
            sgh_status: 'Manutenção',
            hostname: 'OK',
            observation: ''
        },
        {
            id: 38,
            asset: 'Dell Inc.',
            serial: 'Desktop',
            model: 'Optiplex 3020',
            manufacturer: 'A107312',
            type: 'GWXBY02',
            sgh_status: 'Manutenção',
            hostname: 'OK',
            observation: ''
        },
        {
            id: 39,
            asset: 'Dell Inc.',
            serial: 'Desktop',
            model: 'OptiPlex 3050',
            manufacturer: 'SEM_ATIVO_MGC_299',
            type: 'CS0ZRP2',
            sgh_status: 'Manutenção',
            hostname: 'OK',
            observation: ''
        },
        {
            id: 40,
            asset: 'Dell Inc.',
            serial: 'Desktop',
            model: 'OptiPlex 3050',
            manufacturer: 'N003588',
            type: 'CTV1SP2',
            sgh_status: 'Manutenção',
            hostname: 'OK',
            observation: ''
        },
        {
            id: 41,
            asset: 'Dell Inc.',
            serial: 'Desktop',
            model: 'OptiPlex 3050',
            manufacturer: 'SEM_ATIVO_MGC_378',
            type: 'CNDWRP2',
            sgh_status: 'Manutenção',
            hostname: 'OK',
            observation: ''
        },
        {
            id: 42,
            asset: 'Dell Inc.',
            serial: 'Desktop',
            model: 'OptiPlex 3050',
            manufacturer: 'SEM_ATIVO_EUS_13',
            type: 'CTC1SP2',
            sgh_status: 'Manutenção',
            hostname: 'OK',
            observation: ''
        },
        {
            id: 43,
            asset: 'Dell Inc.',
            serial: 'Desktop',
            model: 'Optiplex 3020',
            manufacturer: 'SEM_ATIVO_9522',
            type: 'F9RCY02',
            sgh_status: 'Manutenção',
            hostname: 'OK',
            observation: ''
        },
        {
            id: 44,
            asset: 'Dell Inc.',
            serial: 'Desktop',
            model: 'OptiPlex 3050',
            manufacturer: 'SEM_ATIVO_MGC_334',
            type: 'CRMTRP2',
            sgh_status: 'Manutenção',
            hostname: 'OK',
            observation: 'segunda coluna'
        },
        {
            id: 45,
            asset: 'Dell Inc.',
            serial: 'Desktop',
            model: 'OptiPlex 3050',
            manufacturer: 'SEM_ATIVO_BNF_9',
            type: 'CQ9XRP2',
            sgh_status: 'Manutenção',
            hostname: 'OK',
            observation: ''
        },
        {
            id: 46,
            asset: 'Dell Inc.',
            serial: 'Desktop',
            model: 'OptiPlex 3080',
            manufacturer: 'SEM_ATIVO_STS_68',
            type: '1BHVHF3',
            sgh_status: 'Manutenção',
            hostname: 'OK',
            observation: ''
        },
        {
            id: 47,
            asset: 'Dell Inc.',
            serial: 'Desktop',
            model: 'OptiPlex 3080',
            manufacturer: 'SEM_ATIVO_STS_554',
            type: '574H0D3',
            sgh_status: 'Manutenção',
            hostname: 'OK',
            observation: ''
        },
        {
            id: 48,
            asset: 'Dell Inc.',
            serial: 'Desktop',
            model: 'OptiPlex 3080',
            manufacturer: 'SEM_ATIVO_STS_819',
            type: '9JLF0D3',
            sgh_status: 'Manutenção',
            hostname: 'OK',
            observation: ''
        },
        {
            id: 49,
            asset: 'Dell Inc.',
            serial: 'Desktop',
            model: 'OptiPlex 3080',
            manufacturer: 'N010937',
            type: 'G24H0D3',
            sgh_status: 'Manutenção',
            hostname: 'OK',
            observation: ''
        },
        {
            id: 50,
            asset: 'Dell Inc.',
            serial: 'Desktop',
            model: 'OptiPlex 3080',
            manufacturer: 'N010736',
            type: '8N00L93',
            sgh_status: 'Manutenção',
            hostname: 'OK',
            observation: ''
        },
        {
            id: 51,
            asset: 'Dell Inc.',
            serial: 'Desktop',
            model: 'OptiPlex 3080',
            manufacturer: 'SEM_ATIVO_MGC_489',
            type: 'HY3H0D3',
            sgh_status: 'Manutenção',
            hostname: 'OK',
            observation: ''
        },
        {
            id: 52,
            asset: 'Dell Inc.',
            serial: 'Desktop',
            model: 'OptiPlex 3050',
            manufacturer: 'SEM_ATIVO_J23_249',
            type: 'CRG0SP2',
            sgh_status: 'Manutenção',
            hostname: 'OK',
            observation: ''
        },
        {
            id: 53,
            asset: 'Dell Inc.',
            serial: 'Desktop',
            model: 'OptiPlex 3050',
            manufacturer: 'SEM_ATIVO_STS_1082',
            type: 'CV8VRP2',
            sgh_status: 'Manutenção',
            hostname: 'OK',
            observation: ''
        },
        {
            id: 54,
            asset: 'Dell Inc.',
            serial: 'Desktop',
            model: 'Optiplex 3020',
            manufacturer: 'a109030',
            type: 'FHBCY02',
            sgh_status: 'Manutenção',
            hostname: 'OK',
            observation: ''
        },
        {
            id: 55,
            asset: 'Dell Inc.',
            serial: 'Desktop',
            model: 'OptiPlex 3050',
            manufacturer: 'SEM_ATIVO_EUS_7',
            type: 'CTRXRP2',
            sgh_status: 'Manutenção',
            hostname: 'OK',
            observation: ''
        },
        {
            id: 56,
            asset: 'Dell Inc.',
            serial: 'Desktop',
            model: 'OptiPlex 3050',
            manufacturer: 'SEM_ATIVO_EUS_10',
            type: 'CTKXRP2',
            sgh_status: 'Manutenção',
            hostname: 'OK',
            observation: ''
        },
        {
            id: 57,
            asset: 'Dell Inc.',
            serial: 'Desktop',
            model: 'OptiPlex 3050',
            manufacturer: 'SEM_ATIVO_MGC_343',
            type: 'CS9VRP2',
            sgh_status: 'Manutenção',
            hostname: 'OK',
            observation: ''
        },
        {
            id: 58,
            asset: 'Dell Inc.',
            serial: 'Desktop',
            model: 'OptiPlex 3050',
            manufacturer: 'SEM_ATIVO_MGC_333',
            type: 'CS40SP2',
            sgh_status: 'Manutenção',
            hostname: 'OK',
            observation: ''
        },
        {
            id: 59,
            asset: 'Dell Inc.',
            serial: 'Desktop',
            model: 'OptiPlex 3050',
            manufacturer: 'SEM_ATIVO_STS_388',
            type: 'CNNVRP2',
            sgh_status: 'Manutenção',
            hostname: 'OK',
            observation: 'terceira coluna'
        },
        {
            id: 60,
            asset: 'Positivo SA',
            serial: 'Desktop',
            model: 'Positivo Master D3100',
            manufacturer: 'N004732',
            type: '4A617C98E',
            sgh_status: 'Manutenção',
            hostname: 'OK',
            observation: ''
        },
        {
            id: 61,
            asset: 'Positivo SA',
            serial: 'Desktop',
            model: 'Positivo Master D3100',
            manufacturer: 'SEM_ATIVO_9853',
            type: '4A603HZ83',
            sgh_status: 'Manutenção',
            hostname: 'OK',
            observation: ''
        },
        {
            id: 62,
            asset: 'Positivo SA',
            serial: 'Desktop',
            model: 'Positivo Master D3100',
            manufacturer: 'SEM_ATIVO_9852',
            type: '4A609H40W',
            sgh_status: 'Manutenção',
            hostname: 'OK',
            observation: ''
        },
        {
            id: 63,
            asset: 'Positivo SA',
            serial: 'Desktop',
            model: 'Positivo Master D3100',
            manufacturer: 'SEM_ATIVO_MGC_230',
            type: '4A603J85T',
            sgh_status: 'Manutenção',
            hostname: 'OK',
            observation: ''
        },
        {
            id: 64,
            asset: 'Positivo SA',
            serial: 'Desktop',
            model: 'Positivo Master D2100',
            manufacturer: 'N004169',
            type: '4A603HW5F',
            sgh_status: 'Manutenção',
            hostname: 'OK',
            observation: ''
        },
        {
            id: 65,
            asset: 'Positivo SA',
            serial: 'Desktop',
            model: 'Positivo Master D3100',
            manufacturer: 'SEM_ATIVO_STS_339',
            type: '4A603HN3E',
            sgh_status: 'Manutenção',
            hostname: 'OK',
            observation: ''
        },
        {
            id: 66,
            asset: 'Positivo SA',
            serial: 'Desktop',
            model: 'Positivo Master D2100',
            manufacturer: 'N004187',
            type: '4A609H602',
            sgh_status: 'Manutenção',
            hostname: 'OK',
            observation: ''
        },
        {
            id: 67,
            asset: 'Positivo SA',
            serial: 'Desktop',
            model: 'Positivo Master D3100',
            manufacturer: 'SEM_ATIVO_MGC_229',
            type: '4A603HV7M',
            sgh_status: 'Manutenção',
            hostname: 'OK',
            observation: ''
        },
        {
            id: 68,
            asset: 'Positivo SA',
            serial: 'Desktop',
            model: 'Positivo Master D3100',
            manufacturer: 'SEM_ATIVO_309',
            type: '4A603HP89',
            sgh_status: 'Manutenção',
            hostname: 'OK',
            observation: ''
        },
        {
            id: 69,
            asset: 'Positivo SA',
            serial: 'Desktop',
            model: 'Positivo Master D3100',
            manufacturer: 'N005599',
            type: '4A617C84R',
            sgh_status: 'Manutenção',
            hostname: 'OK',
            observation: ''
        },
        {
            id: 70,
            asset: 'Positivo SA',
            serial: 'Desktop',
            model: 'Positivo Master D3100',
            manufacturer: 'SEM_ATIVO_310',
            type: '4A603HQ1D',
            sgh_status: 'Manutenção',
            hostname: 'OK',
            observation: 'quarta coluna'
        }
    ]
}

export const sghDB: SghMachineDTO[] = [
    {
        id: 1,
        asset: 'N001216',
        serial: '96GC2M2',
        model: 'OptiPlex 3050',
        manufacturer: 'Dell Inc.',
        cpu: 'Intel(R) Core(TM) i3',
        type: 'Desktop',
        site: 'BRF',
        status: 'Perdido',
        possession: 'LEGADO',
        operation: '-'
    },
    {
        id: 2,
        asset: 'N013331',
        serial: '1Y3H0D3',
        model: 'OptiPlex 3080',
        manufacturer: 'Dell Inc.',
        cpu: 'Intel(R) Core(TM) i5',
        type: 'Desktop',
        site: 'SJO',
        status: 'Produção',
        possession: 'LEGADO',
        operation: 'SANTANDER PÓS-VENDA'
    },
    {
        id: 3,
        asset: 'N013341',
        serial: '7YBQ9N3',
        model: 'Latitude 3420',
        manufacturer: 'Dell Inc.',
        cpu: '11th Gen Intel(R) Core(TM) i5',
        type: 'Notebook',
        site: 'PIN',
        status: 'Produção',
        possession: 'LEGADO',
        operation: 'SDM BRF'
    },
    {
        id: 4,
        asset: 'N000117',
        serial: '6X9D2M2',
        model: 'OptiPlex 3050',
        manufacturer: 'Dell Inc.',
        cpu: 'Intel(R) Core(TM) i3',
        type: 'Desktop',
        site: 'ENE',
        status: 'Produção',
        possession: 'LEGADO',
        operation: 'ENEL LOJAS SP'
    },
    {
        id: 5,
        asset: 'N001368',
        serial: '6VPJ2M2',
        model: 'OptiPlex 3050',
        manufacturer: 'Dell Inc.',
        cpu: 'Intel(R) Core(TM) i3',
        type: 'Desktop',
        site: 'SJO',
        status: 'Manutenção',
        possession: 'LEGADO',
        operation: 'SIMPLIC SJO'
    },
    {
        id: 6,
        asset: 'N001383',
        serial: '6XG82M2',
        model: 'OptiPlex 3050',
        manufacturer: 'Dell Inc.',
        cpu: 'Intel(R) Core(TM) i3',
        type: 'Desktop',
        site: 'CLD',
        status: 'Perdido',
        possession: 'LEGADO',
        operation: 'NEOENERGIA CLD'
    },
    {
        id: 7,
        asset: 'N004497',
        serial: 'PE03T5RB',
        model: 'B320-14IKB Laptop - Type 81CC',
        manufacturer: 'Lenovo',
        cpu: 'Intel(R) Core(TM) i3',
        type: 'Notebook',
        site: 'GOT',
        status: 'Manutenção',
        possession: 'LEGADO',
        operation: 'GOT'
    },
    {
        id: 8,
        asset: 'A119732',
        serial: 'BRJ446C3MR',
        model: 'HP ProDesk 600 G1 DM',
        manufacturer: 'Hewlett-Packard',
        cpu: 'Intel(R) Core(TM) i3',
        type: 'Desktop',
        site: 'JBT',
        status: 'Estoque',
        possession: 'LEGADO',
        operation: 'NEOENERGIA CLD'
    },
    {
        id: 9,
        asset: 'A119792',
        serial: 'BRJ446C4MD',
        model: 'HP ProDesk 600 G1 DM',
        manufacturer: 'Hewlett-Packard',
        cpu: 'Intel(R) Core(TM) i3',
        type: 'Desktop',
        site: 'CLD',
        status: 'Férias',
        possession: 'LEGADO',
        operation: 'NEOENERGIA CLD'
    },
    {
        id: 10,
        asset: 'A119940',
        serial: 'BRJ446C3ND',
        model: 'HP ProDesk 600 G1 DM',
        manufacturer: 'Hewlett-Packard',
        cpu: 'Intel(R) Core(TM) i3',
        type: 'Desktop',
        site: 'CLD',
        status: 'Produção',
        possession: 'LEGADO',
        operation: 'NEOENERGIA CLD'
    },
    {
        id: 11,
        asset: 'A063504',
        serial: 'BRG040F5MR',
        model: 'HP Compaq 6000 Pro SFF PC',
        manufacturer: 'Hewlett-Packard',
        cpu: 'Intel(R) Core(TM)2 Duo',
        type: 'Desktop',
        site: 'SJO',
        status: 'Descarte',
        possession: 'LEGADO',
        operation: 'Descarte'
    },
    {
        id: 12,
        asset: 'A094576',
        serial: 'BRG237FG6D',
        model: 'HP Compaq Pro 6300 SFF',
        manufacturer: 'Hewlett-Packard',
        cpu: 'Intel(R) Core(TM) i3',
        type: 'Desktop',
        site: 'SJO',
        status: 'Descarte',
        possession: 'LEGADO',
        operation: 'Descarte'
    },
    {
        id: 13,
        asset: 'A108490',
        serial: '9QQFLZ1',
        model: 'OptiPlex 3010',
        manufacturer: 'Dell Inc.',
        cpu: 'Intel(R) Core(TM) i5',
        type: 'Desktop',
        site: 'JBT',
        status: 'Estoque',
        possession: 'LEGADO',
        operation: 'FORA DA CONSOLE (KSP)'
    },
    {
        id: 14,
        asset: 'N000002',
        serial: 'PE02PDFQ',
        model: 'ThinkPad T460 Laptop',
        manufacturer: 'Lenovo',
        cpu: 'Intel(R) Core(TM) i5',
        type: 'Notebook',
        site: 'PIN',
        status: 'Férias',
        possession: 'NEOBPO',
        operation: ''
    },
    {
        id: 15,
        asset: 'N000003',
        serial: 'PE02PDH2',
        model: 'ThinkPad T460 Laptop',
        manufacturer: 'Lenovo',
        cpu: 'Intel(R) Core(TM) i5',
        type: 'Notebook',
        site: 'GOT',
        status: 'Manutenção',
        possession: 'NEOBPO',
        operation: 'GOT'
    },
    {
        id: 16,
        asset: 'N013649',
        serial: 'PE07FNN2',
        model: 'Lenovo E14',
        manufacturer: 'Lenovo',
        cpu: 'Intel(R) Core(TM) i5',
        type: 'Notebook',
        site: 'ENE',
        status: 'Produção',
        possession: 'NEOBPO',
        operation: 'ENEL LOJAS SP'
    },
    {
        id: 17,
        asset: 'N000005',
        serial: 'PE02PDH7',
        model: 'ThinkPad T460 Laptop',
        manufacturer: 'Lenovo',
        cpu: 'Intel(R) Core(TM) i5',
        type: 'Notebook',
        site: 'CLD',
        status: 'Produção',
        possession: 'NEOBPO',
        operation: 'ALELO OFFICERS'
    },
    {
        id: 18,
        asset: 'N001612',
        serial: 'PE01RUB0',
        model: 'V310-14ISK Laptop - Type 80UF',
        manufacturer: 'Lenovo',
        cpu: 'Intel(R) Core(TM) i3',
        type: 'Notebook',
        site: 'GOT',
        status: 'Manutenção',
        possession: 'NEOBPO',
        operation: 'GOT'
    },
    {
        id: 19,
        asset: 'N001613',
        serial: 'PE02RUAR',
        model: 'V310-14ISK Laptop - Type 80UF',
        manufacturer: 'Lenovo',
        cpu: 'Intel(R) Core(TM) i3',
        type: 'Notebook',
        site: 'GOT',
        status: 'Manutenção',
        possession: 'NEOBPO',
        operation: 'GOT'
    },
    {
        id: 20,
        asset: 'N000008',
        serial: 'PE02PDHE',
        model: 'ThinkPad T460 Laptop',
        manufacturer: 'Lenovo',
        cpu: 'Intel(R) Core(TM) i5',
        type: 'Notebook',
        site: 'CLD',
        status: 'Produção',
        possession: 'NEOBPO',
        operation: 'ALELO OFFICERS'
    },
    {
        id: 21,
        asset: 'N000009',
        serial: 'PE02PDHG',
        model: 'ThinkPad T460 Laptop',
        manufacturer: 'Lenovo',
        cpu: 'Intel(R) Core(TM) i5',
        type: 'Notebook',
        site: 'GOT',
        status: 'Manutenção',
        possession: 'NEOBPO',
        operation: 'GOT'
    },
    {
        id: 22,
        asset: 'N000011',
        serial: 'PE01GG3A',
        model: 'ThinkPad L440',
        manufacturer: 'Lenovo',
        cpu: 'Intel(R) Core(TM) i3',
        type: 'Notebook',
        site: 'GOT',
        status: 'Em descarte',
        possession: 'NEOBPO',
        operation: 'GOT'
    },
    {
        id: 23,
        asset: 'N000012',
        serial: 'PE02PDGY',
        model: 'ThinkPad T460 Laptop',
        manufacturer: 'Lenovo',
        cpu: 'Intel(R) Core(TM) i5',
        type: 'Notebook',
        site: 'GOT',
        status: 'Manutenção',
        possession: 'NEOBPO',
        operation: 'GOT'
    },
    {
        id: 24,
        asset: 'N000014',
        serial: 'PE02PDHJ',
        model: 'ThinkPad T460 Laptop',
        manufacturer: 'Lenovo',
        cpu: 'Intel(R) Core(TM) i5',
        type: 'Notebook',
        site: 'J23',
        status: 'Férias',
        possession: 'NEOBPO',
        operation: 'ALELO VT'
    },
    {
        id: 25,
        asset: 'N000015',
        serial: 'PE02PDHK',
        model: 'ThinkPad T460 Laptop',
        manufacturer: 'Lenovo',
        cpu: 'Intel(R) Core(TM) i5',
        type: 'Notebook',
        site: 'MGC',
        status: 'Estoque',
        possession: 'NEOBPO',
        operation: 'AMIL'
    },
    {
        id: 26,
        asset: 'N000016',
        serial: 'PE02PDH5',
        model: 'ThinkPad T460 Laptop',
        manufacturer: 'Lenovo',
        cpu: 'Intel(R) Core(TM) i5',
        type: 'Notebook',
        site: 'CLD',
        status: 'Produção',
        possession: 'NEOBPO',
        operation: 'ALELO OFFICERS'
    },
    {
        id: 27,
        asset: 'N004449',
        serial: 'PE03GYAR',
        model: 'B320-14IKB Laptop - Type 81CC',
        manufacturer: 'Lenovo',
        cpu: 'Intel(R) Core(TM) i3',
        type: 'Notebook',
        site: 'PIN',
        status: 'Manutenção',
        possession: 'NEOBPO',
        operation: 'SDM PIN'
    },
    {
        id: 28,
        asset: 'N002918',
        serial: 'PE02L5ED',
        model: 'ThinkPad T460 Laptop',
        manufacturer: 'Lenovo',
        cpu: 'Intel(R) Core(TM) i5',
        type: 'Notebook',
        site: 'CLD',
        status: 'Produção',
        possession: 'NEOBPO',
        operation: 'ALELO OFFICERS'
    },
    {
        id: 29,
        asset: 'N000020',
        serial: 'PE02PDH9',
        model: 'ThinkPad T460 Laptop',
        manufacturer: 'Lenovo',
        cpu: 'Intel(R) Core(TM) i5',
        type: 'Notebook',
        site: 'GOT',
        status: 'Manutenção',
        possession: 'NEOBPO',
        operation: 'GOT'
    },
    {
        id: 30,
        asset: 'N004450',
        serial: 'PE03GXY9',
        model: 'B320-14IKB Laptop - Type 81CC',
        manufacturer: 'Lenovo',
        cpu: 'Intel(R) Core(TM) i3',
        type: 'Notebook',
        site: 'CLD',
        status: 'Produção',
        possession: 'NEOBPO',
        operation: 'ALELO OFFICERS'
    },
    {
        id: 31,
        asset: 'N004452',
        serial: 'PE03GYAL',
        model: 'B320-14IKB Laptop - Type 81CC',
        manufacturer: 'Lenovo',
        cpu: 'Intel(R) Core(TM) i3',
        type: 'Notebook',
        site: 'GOT',
        status: 'Manutenção',
        possession: 'NEOBPO',
        operation: 'GOT'
    },
    {
        id: 32,
        asset: 'N000023',
        serial: 'PE02PDH8',
        model: 'ThinkPad T460 Laptop',
        manufacturer: 'Lenovo',
        cpu: 'Intel(R) Core(TM) i5',
        type: 'Notebook',
        site: 'PIN',
        status: 'Estoque',
        possession: 'NEOBPO',
        operation: 'RH'
    },
    {
        id: 33,
        asset: 'N000024',
        serial: 'PE02PDGX',
        model: 'ThinkPad T460 Laptop',
        manufacturer: 'Lenovo',
        cpu: 'Intel(R) Core(TM) i5',
        type: 'Notebook',
        site: 'CLD',
        status: 'Produção',
        possession: 'NEOBPO',
        operation: 'ALELO OFFICERS'
    },
    {
        id: 34,
        asset: 'N000025',
        serial: 'PE02PDH1',
        model: 'ThinkPad T460 Laptop',
        manufacturer: 'Lenovo',
        cpu: 'Intel(R) Core(TM) i5',
        type: 'Notebook',
        site: 'CLD',
        status: 'Produção',
        possession: 'NEOBPO',
        operation: 'ALELO OFFICERS'
    },
    {
        id: 35,
        asset: 'N000026',
        serial: 'PE02PDHB',
        model: 'ThinkPad T460 Laptop',
        manufacturer: 'Lenovo',
        cpu: 'Intel(R) Core(TM) i5',
        type: 'Notebook',
        site: 'PIN',
        status: 'Produção',
        possession: 'NEOBPO',
        operation: ''
    },
    {
        id: 36,
        asset: 'N002919',
        serial: 'PE03BHKE',
        model: 'B320-14IKB Laptop - Type 81CC',
        manufacturer: 'Lenovo',
        cpu: 'Intel(R) Core(TM) i3',
        type: 'Notebook',
        site: 'PIN',
        status: 'Produção',
        possession: 'NEOBPO',
        operation: 'SUPRIMENTOS'
    },
    {
        id: 37,
        asset: 'N002920',
        serial: 'PE03BHJL',
        model: 'B320-14IKB Laptop - Type 81CC',
        manufacturer: 'Lenovo',
        cpu: 'Intel(R) Core(TM) i3',
        type: 'Notebook',
        site: 'CLD',
        status: 'Produção',
        possession: 'NEOBPO',
        operation: 'ALELO OFFICERS'
    },
    {
        id: 38,
        asset: 'N002921',
        serial: 'PE03BHQ3',
        model: 'B320-14IKB Laptop - Type 81CC',
        manufacturer: 'Lenovo',
        cpu: 'Intel(R) Core(TM) i3',
        type: 'Notebook',
        site: 'JBT',
        status: 'Férias',
        possession: 'NEOBPO',
        operation: 'SDM JBT'
    },
    {
        id: 39,
        asset: 'N002922',
        serial: 'PE03BHPW',
        model: 'B320-14IKB Laptop - Type 81CC',
        manufacturer: 'Lenovo',
        cpu: 'Intel(R) Core(TM) i3',
        type: 'Notebook',
        site: 'GOT',
        status: 'Manutenção',
        possession: 'NEOBPO',
        operation: 'GOT'
    },
    {
        id: 40,
        asset: 'N002742',
        serial: 'PE03GY1V',
        model: 'B320-14IKB Laptop - Type 81CC',
        manufacturer: 'Lenovo',
        cpu: 'Intel(R) Core(TM) i3',
        type: 'Notebook',
        site: 'J23',
        status: 'Manutenção',
        possession: 'NEOBPO',
        operation: 'SDM J23'
    },
    {
        id: 41,
        asset: 'N002743',
        serial: 'PE03GY15',
        model: 'B320-14IKB Laptop - Type 81CC',
        manufacturer: 'Lenovo',
        cpu: 'Intel(R) Core(TM) i3',
        type: 'Notebook',
        site: 'JBT',
        status: 'Manutenção',
        possession: 'NEOBPO',
        operation: 'RH'
    },
    {
        id: 42,
        asset: 'N004453',
        serial: 'PE03GYC2',
        model: 'B320-14IKB Laptop - Type 81CC',
        manufacturer: 'Lenovo',
        cpu: 'Intel(R) Core(TM) i3',
        type: 'Notebook',
        site: 'GOT',
        status: 'Em descarte',
        possession: 'NEOBPO',
        operation: 'GOT'
    },
    {
        id: 43,
        asset: 'N004454',
        serial: 'PE03GYCP',
        model: 'B320-14IKB Laptop - Type 81CC',
        manufacturer: 'Lenovo',
        cpu: 'Intel(R) Core(TM) i3',
        type: 'Notebook',
        site: 'GOT',
        status: 'Manutenção',
        possession: 'NEOBPO',
        operation: 'GOT'
    },
    {
        id: 44,
        asset: 'N002746',
        serial: 'PE03GY2E',
        model: 'B320-14IKB Laptop - Type 81CC',
        manufacturer: 'Lenovo',
        cpu: 'Intel(R) Core(TM) i3',
        type: 'Notebook',
        site: 'GOT',
        status: 'Manutenção',
        possession: 'NEOBPO',
        operation: 'GOT'
    },
    {
        id: 45,
        asset: 'N003861',
        serial: 'PE03F17M',
        model: 'B320-14IKB Laptop - Type 81CC',
        manufacturer: 'Lenovo',
        cpu: 'Intel(R) Core(TM) i3',
        type: 'Notebook',
        site: 'GOT',
        status: 'Manutenção',
        possession: 'NEOBPO',
        operation: 'GOT'
    },
    {
        id: 46,
        asset: 'N003862',
        serial: 'PE02PDH3',
        model: 'ThinkPad T460 Laptop',
        manufacturer: 'Lenovo',
        cpu: 'Intel(R) Core(TM) i5',
        type: 'Notebook',
        site: 'SJO',
        status: 'Perdido',
        possession: 'NEOBPO',
        operation: '-'
    },
    {
        id: 47,
        asset: 'N003863',
        serial: 'PE03F15Q',
        model: 'B320-14IKB Laptop - Type 81CC',
        manufacturer: 'Lenovo',
        cpu: 'Intel(R) Core(TM) i3',
        type: 'Notebook',
        site: 'CLD',
        status: 'Produção',
        possession: 'NEOBPO',
        operation: 'ALELO OFFICERS'
    },
    {
        id: 48,
        asset: 'N003864',
        serial: 'PE03F15A',
        model: 'B320-14IKB Laptop - Type 81CC',
        manufacturer: 'Lenovo',
        cpu: 'Intel(R) Core(TM) i3',
        type: 'Notebook',
        site: 'CLD',
        status: 'Produção',
        possession: 'NEOBPO',
        operation: 'ALELO OFFICERS'
    },
    {
        id: 49,
        asset: 'N003865',
        serial: 'PE03F16W',
        model: 'B320-14IKB Laptop - Type 81CC',
        manufacturer: 'Lenovo',
        cpu: 'Intel(R) Core(TM) i3',
        type: 'Notebook',
        site: 'CLD',
        status: 'Produção',
        possession: 'NEOBPO',
        operation: 'ALELO OFFICERS'
    },
    {
        id: 50,
        asset: 'N003913',
        serial: '4A522G743',
        model: 'Positivo S14SL01',
        manufacturer: 'Positivo SA',
        cpu: 'Intel(R) Core(TM) i5',
        type: 'Notebook',
        site: 'GOT',
        status: 'Manutenção',
        possession: 'NEOBPO',
        operation: 'GOT'
    },
    {
        id: 51,
        asset: 'N003914',
        serial: '4A522G567',
        model: 'Positivo S14SL01',
        manufacturer: 'Positivo SA',
        cpu: 'Intel(R) Core(TM) i5',
        type: 'Notebook',
        site: 'GOT',
        status: 'Manutenção',
        possession: 'NEOBPO',
        operation: 'GOT'
    },
    {
        id: 52,
        asset: 'N003915',
        serial: '4A522GF07',
        model: 'Positivo S14SL01',
        manufacturer: 'Positivo SA',
        cpu: 'Intel(R) Core(TM) i5',
        type: 'Notebook',
        site: 'SJO',
        status: 'Férias',
        possession: 'NEOBPO',
        operation: 'SESMT'
    },
    {
        id: 53,
        asset: 'N003916',
        serial: '4A522G91U',
        model: 'Positivo S14SL01',
        manufacturer: 'Positivo SA',
        cpu: 'Intel(R) Core(TM) i5',
        type: 'Notebook',
        site: 'GOT',
        status: 'Manutenção',
        possession: 'NEOBPO',
        operation: 'GOT'
    },
    {
        id: 54,
        asset: 'N004455',
        serial: 'PE03GYBF',
        model: 'B320-14IKB Laptop - Type 81CC',
        manufacturer: 'Lenovo',
        cpu: 'Intel(R) Core(TM) i3',
        type: 'Notebook',
        site: 'PTM',
        status: 'Produção',
        possession: 'NEOBPO',
        operation: 'SESMT'
    },
    {
        id: 55,
        asset: 'N004493',
        serial: 'PE03T0RN',
        model: 'B320-14IKB Laptop - Type 81CC',
        manufacturer: 'Lenovo',
        cpu: 'Intel(R) Core(TM) i3',
        type: 'Notebook',
        site: 'GOT',
        status: 'Manutenção',
        possession: 'NEOBPO',
        operation: 'GOT'
    },
    {
        id: 56,
        asset: 'N004494',
        serial: 'PE03T0QV',
        model: 'B320-14IKB Laptop - Type 81CC',
        manufacturer: 'Lenovo',
        cpu: 'Intel(R) Core(TM) i3',
        type: 'Notebook',
        site: 'PTM',
        status: 'Produção',
        possession: 'NEOBPO',
        operation: 'OPERAÇÃO DATA CENTER'
    },
    {
        id: 57,
        asset: 'N004495',
        serial: 'PE03T127',
        model: 'B320-14IKB Laptop - Type 81CC',
        manufacturer: 'Lenovo',
        cpu: 'Intel(R) Core(TM) i3',
        type: 'Notebook',
        site: 'GOT',
        status: 'Manutenção',
        possession: 'NEOBPO',
        operation: 'GOT'
    },
    {
        id: 58,
        asset: 'N004496',
        serial: 'PE03T0R5',
        model: 'B320-14IKB Laptop - Type 81CC',
        manufacturer: 'Lenovo',
        cpu: 'Intel(R) Core(TM) i3',
        type: 'Notebook',
        site: 'JBT',
        status: 'Estoque',
        possession: 'NEOBPO',
        operation: 'SDM JBT'
    },
    {
        id: 59,
        asset: 'N004456',
        serial: 'PE03GYBT',
        model: 'B320-14IKB Laptop - Type 81CC',
        manufacturer: 'Lenovo',
        cpu: 'Intel(R) Core(TM) i3',
        type: 'Notebook',
        site: 'CLD',
        status: 'Produção',
        possession: 'NEOBPO',
        operation: 'ALELO OFFICERS'
    },
    {
        id: 60,
        asset: 'N003931',
        serial: 'PE03T5SM',
        model: 'B320-14IKB Laptop - Type 81CC',
        manufacturer: 'Lenovo',
        cpu: 'Intel(R) Core(TM) i3',
        type: 'Notebook',
        site: 'CLD',
        status: 'Produção',
        possession: 'NEOBPO',
        operation: 'ALELO OFFICERS'
    },
    {
        id: 61,
        asset: 'SEMATIVO_31',
        serial: 'PE03T5SQ',
        model: 'B320-14IKB Laptop - Type 81CC',
        manufacturer: 'Lenovo',
        cpu: 'Intel(R) Core(TM) i3',
        type: 'Notebook',
        site: 'CLD',
        status: 'Produção',
        possession: 'NEOBPO',
        operation: 'ALELO OFFICERS'
    },
    {
        id: 62,
        asset: 'N004457',
        serial: 'PE03GYC8',
        model: 'B320-14IKB Laptop - Type 81CC',
        manufacturer: 'Lenovo',
        cpu: 'Intel(R) Core(TM) i3',
        type: 'Notebook',
        site: 'CLD',
        status: 'Férias',
        possession: 'NEOBPO',
        operation: 'ALELO OFFICERS'
    },
    {
        id: 63,
        asset: 'N004458',
        serial: 'PE03GYCR',
        model: 'B320-14IKB Laptop - Type 81CC',
        manufacturer: 'Lenovo',
        cpu: 'Intel(R) Core(TM) i3',
        type: 'Notebook',
        site: 'MGC',
        status: 'Produção',
        possession: 'NEOBPO',
        operation: 'SDM MGC'
    },
    {
        id: 64,
        asset: 'N004500',
        serial: 'PE03T5VF',
        model: 'B320-14IKB Laptop - Type 81CC',
        manufacturer: 'Lenovo',
        cpu: 'Intel(R) Core(TM) i3',
        type: 'Notebook',
        site: 'ENE',
        status: 'Férias',
        possession: 'NEOBPO',
        operation: 'SDM LOJAS ENEL'
    },
    {
        id: 65,
        asset: 'N004459',
        serial: 'PE03GYC5',
        model: 'B320-14IKB Laptop - Type 81CC',
        manufacturer: 'Lenovo',
        cpu: 'Intel(R) Core(TM) i3',
        type: 'Notebook',
        site: 'GOT',
        status: 'Manutenção',
        possession: 'NEOBPO',
        operation: 'GOT'
    },
    {
        id: 66,
        asset: 'N005605',
        serial: 'PE04GK4K',
        model: 'B330-15IKBR Laptop - Type 81M1',
        manufacturer: 'Lenovo',
        cpu: 'Intel(R) Core(TM) i3',
        type: 'Notebook',
        site: 'GOT',
        status: 'Manutenção',
        possession: 'NEOBPO',
        operation: 'GOT'
    },
    {
        id: 67,
        asset: 'N005606',
        serial: 'PE04GK0F',
        model: 'B330-15IKBR Laptop - Type 81M1',
        manufacturer: 'Lenovo',
        cpu: 'Intel(R) Core(TM) i3',
        type: 'Notebook',
        site: 'SJO',
        status: 'Perdido',
        possession: 'NEOBPO',
        operation: '-'
    },
    {
        id: 68,
        asset: 'N004460',
        serial: 'PE03GY4H',
        model: 'B320-14IKB Laptop - Type 81CC',
        manufacturer: 'Lenovo',
        cpu: 'Intel(R) Core(TM) i3',
        type: 'Notebook',
        site: 'GOT',
        status: 'Manutenção',
        possession: 'NEOBPO',
        operation: 'GOT'
    },
    {
        id: 69,
        asset: 'N005608',
        serial: 'PE04GK40',
        model: 'B330-15IKBR Laptop - Type 81M1',
        manufacturer: 'Lenovo',
        cpu: 'Intel(R) Core(TM) i3',
        type: 'Notebook',
        site: 'CLD',
        status: 'Produção',
        possession: 'NEOBPO',
        operation: 'ALELO OFFICERS'
    },
    {
        id: 70,
        asset: 'N005609',
        serial: 'PE04GK47',
        model: 'B330-15IKBR Laptop - Type 81M1',
        manufacturer: 'Lenovo',
        cpu: 'Intel(R) Core(TM) i3',
        type: 'Notebook',
        site: 'CLD',
        status: 'Produção',
        possession: 'NEOBPO',
        operation: 'ALELO OFFICERS'
    },
    {
        id: 71,
        asset: 'N005610',
        serial: 'PE04GK4A',
        model: 'B330-15IKBR Laptop - Type 81M1',
        manufacturer: 'Lenovo',
        cpu: 'Intel(R) Core(TM) i3',
        type: 'Notebook',
        site: 'GOT',
        status: 'Manutenção',
        possession: 'NEOBPO',
        operation: 'GOT'
    },
    {
        id: 72,
        asset: 'N004462',
        serial: 'PE03GXUZ',
        model: 'B320-14IKB Laptop - Type 81CC',
        manufacturer: 'Lenovo',
        cpu: 'Intel(R) Core(TM) i3',
        type: 'Notebook',
        site: 'ENE',
        status: 'Produção',
        possession: 'NEOBPO',
        operation: 'ENEL LOJAS SP'
    },
    {
        id: 73,
        asset: 'N004463',
        serial: 'PE03GYCC',
        model: 'B320-14IKB Laptop - Type 81CC',
        manufacturer: 'Lenovo',
        cpu: 'Intel(R) Core(TM) i3',
        type: 'Notebook',
        site: 'GOT',
        status: 'Em descarte',
        possession: 'NEOBPO',
        operation: 'GOT'
    }
]